name: flutter_wiki_search_app
description: A new Flutter Wikipedia application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.3
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.3+6
  cached_network_image: ^1.1.2+1
  flutter_bloc: ^0.10.1
  webview_flutter: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

